### ISSUE TITLE
Do i have to make an action if i only use this client

### ISSUE THREAD

**Issue by aelamel** [googleapis/google-api-php-client#1643]
Hi,

i'm using the V2.2.3 and i'm wondering if i have to update something in my code due to the new update of the Cloud Storage API (adding storage.googleapis.com).

Thanks.

**Comment by jdpedrie** [comment]
So far as I'm aware, there haven't been any breaking changes in the API. Can you be a bit more specific about what you're asking? Do you have a code sample?

**Comment by aelamel** [comment]
To be more specific, i'm using the client in a Symfony application in order to interact with Cloud Storage (downloading and uploading through gaufrette and VichUploader libraries).

The integration with Gaufrette looks like this : 

```
<?php

namespace AppBundle\Factory;
use Google_Service_Storage;

class GoogleCloudStorageServiceFactory {

    public function createService() {
        // creating the google client
        $client = new \Google_Client();

        // setting the service account credentials
        $client->setAuthConfig('path_to_json_file');
        $client->setScopes([Google_Service_Storage::DEVSTORAGE_READ_WRITE]);
        // creating and returning the service
        return new \Google_Service_Storage($client);
    }

}
```

services.yml

```
app.google_cloud_storage.service:
    class: \Google_Service_Storage
    factory: [AppBundle\Factory\GoogleCloudStorageServiceFactory, createService]


knp_gaufrette:
    stream_wrapper: ~
    adapters:
        gcs_images:
            google_cloud_storage:
                service_id: 'app.google_cloud_storage.service'
                bucket_name: 'images'
filesystems:
    gcs_images_fs:
        adapter: gcs_images

vich_uploader:
    db_driver: orm
    storage: gaufrette   
    mappings:
        motors_files:
            upload_destination: gcs_images_fs
            namer: vich_uploader.namer_origname
```

For downloading files without the help of gaufrette, i'm doing something like this : 

```
<?php

namespace MyFM\WebPortalBundle\Service;

use GuzzleHttp\Psr7\Request;

class GoogleCloudStorageDownloader
{
    /** @var  \Google_Service_Storage */
    private $storageService;

    /**
     * @param \Google_Service_Storage $storageService
     */
    public function setStorageService($storageService)
    {
        $this->storageService = $storageService;
    }

    public function download($source, $fileName, $destination)
    {
        $file = $this->storageService->objects->get('bucket_name', 'path_to_file_in_bucket');

        $request = new Request('GET', $file['mediaLink']);
        $client = $this->storageService->getClient();
        $response = $client->authorize()->send($request);
        file_put_contents('path_to_file_where_to_put_file_content', $response->getBody());
    }
}

``` 
I'm wondering if there something to change due to the upcoming update in the API.

Thanks for you answer in advance.

**Comment by aelamel** [comment]
To be more specific, i'm using the client in a Symfony application in order to interact with Cloud Storage (downloading and uploading through gaufrette and VichUploader libraries).

The integration with Gaufrette looks like this : 

```
<?php

namespace AppBundle\Factory;
use Google_Service_Storage;

class GoogleCloudStorageServiceFactory {

    public function createService() {
        // creating the google client
        $client = new \Google_Client();

        // setting the service account credentials
        $client->setAuthConfig('path_to_json_file');
        $client->setScopes([Google_Service_Storage::DEVSTORAGE_READ_WRITE]);
        // creating and returning the service
        return new \Google_Service_Storage($client);
    }

}
```

services.yml

```
app.google_cloud_storage.service:
    class: \Google_Service_Storage
    factory: [AppBundle\Factory\GoogleCloudStorageServiceFactory, createService]


knp_gaufrette:
    stream_wrapper: ~
    adapters:
        gcs_images:
            google_cloud_storage:
                service_id: 'app.google_cloud_storage.service'
                bucket_name: 'images'
filesystems:
    gcs_images_fs:
        adapter: gcs_images

vich_uploader:
    db_driver: orm
    storage: gaufrette   
    mappings:
        motors_files:
            upload_destination: gcs_images_fs
            namer: vich_uploader.namer_origname
```

For downloading files without the help of gaufrette, i'm doing something like this : 

```
<?php

namespace AppBundle\Service;

use GuzzleHttp\Psr7\Request;

class GoogleCloudStorageDownloader
{
    /** @var  \Google_Service_Storage */
    private $storageService;

    /**
     * @param \Google_Service_Storage $storageService
     */
    public function setStorageService($storageService)
    {
        $this->storageService = $storageService;
    }

    public function download($source, $fileName, $destination)
    {
        $file = $this->storageService->objects->get('bucket_name', 'path_to_file_in_bucket');

        $request = new Request('GET', $file['mediaLink']);
        $client = $this->storageService->getClient();
        $response = $client->authorize()->send($request);
        file_put_contents('path_to_file_where_to_put_file_content', $response->getBody());
    }
}

``` 
I'm wondering if there something to change due to the upcoming update in the API.

Thanks for you answer in advance.
