### ISSUE TITLE
Fatal error: Uncaught Google_Exception: Invalid client secret JSON file. in /somepath/lib/vendor/google/apiclient/src/Google/Client.php

### ISSUE THREAD

**Issue by basd82** [googleapis/google-api-php-client#2481]
#### Environment details

  - OS: ubuntu 20.04
  - PHP version: 8.2.8
  - Package name and version:

#### Steps to reproduce

Try to get oath to work 
The api reports json file is missing but it is there, and it is unchanged like downloaded from google dev.

#### Code example
google login.php
```
php
$client = new Google\Client();
$authfile = 'somepath/client_secret.json';
$client->setAuthConfig($authfile);
client->setRedirectUri('https://topsecret.domain.tld/oauth2callback.php');
$client->setAccessType('offline');        // offline access
$client->setIncludeGrantedScopes(true);   // incremental auth
$client->addScope(Google\Service\Fitness::FITNESS_ACTIVITY_READ);
$auth_url = $client->createAuthUrl();
header('Location: ' . filter_var($auth_url, FILTER_SANITIZE_URL));
if (isset($_SESSION['access_token']) && $_SESSION['access_token'])
{
    $client->setAccessToken($_SESSION['access_token']);
    echo "Ingelogd met access tolken: " . $_SESSION['access_token'];
}
else
{
    $redirect_uri = 'https://topsecret.domain.tld/oauth2callback.php';
    header('Location: ' . filter_var($redirect_uri, FILTER_SANITIZE_URL));
}

```

json auth file

```yaml
{
  "web": {
    "client_id": "topsecretstuff.apps.googleusercontent.com",
    "project_id": "health-42",
    "auth_uri": "https://accounts.google.com/o/oauth2/auth",
    "token_uri": "https://oauth2.googleapis.com/token",
    "auth_provider_x509_cert_url": "https://www.googleapis.com/oauth2/v1/certs",
    "client_secret": "GOCSPX-topsecretstuff",
    "redirect_uris": [
      "https://topsecret.domain.tld/oauth2callback.php",
      "https://topsecret.domain.tld/googlelogin.php"
    ]
  }
}
```
